services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - corretora-network

  backend:
    build:
      context: ./Back-corretora
    container_name: backend-api
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/trading
      - FRONTEND_URL=${FRONTEND_URL:-https://brokerblackpearl.com.br}
      - API_URL=${API_URL:-https://brokerblackpearl.com.br/server-api}
    depends_on:
      - mongodb
    networks:
      - corretora-network

  frontend:
    build:
      context: ./Front-corretora
      args:
        - NEXT_PUBLIC_API_URL=/server-api
        - NEXT_PUBLIC_WS_URL=/ws
    environment:
      - INTERNAL_API_URL=http://backend:8080
    container_name: frontend-next
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - corretora-network

  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # SSL Certificates from the Host (VPS)
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - corretora-network

networks:
  corretora-network:
    driver: bridge

volumes:
  mongo-data:
