services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-pt
    ports:
      - "27018:27017"
    volumes:
      - mongo-data-pt:/data/db
    networks:
      - corretora-pt-network

  backend:
    build:
      context: ./Back-corretora
    container_name: backend-api-pt
    ports:
      - "8081:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/trading
      - FRONTEND_URL=${FRONTEND_URL:-https://blackpearlbroker.com}
      - API_URL=${API_URL:-https://blackpearlbroker.com/server-api}
    depends_on:
      - mongodb
    networks:
      - corretora-pt-network

  frontend:
    build:
      context: ./Front-corretora
      args:
        - NEXT_PUBLIC_API_URL=/server-api
        - NEXT_PUBLIC_WS_URL=/ws
    environment:
      - INTERNAL_API_URL=http://backend:8080
    container_name: frontend-next-pt
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - corretora-pt-network

networks:
  corretora-pt-network:
    driver: bridge

volumes:
  mongo-data-pt:
